version: '3'
name: offline-audio-app

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8003:8003"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health_check"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./backend/models:/app/backend/models
      - ./backend/logs:/app/backend/logs

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge